[project]
name = "pyspartaproj"
version = "0.0.1"
requires-python = ">=3.13.1"

[dependency-groups]
dev = ["ruff>=0.8.3"]

[tool.ruff]
cache-dir = "./.temp/.ruff_cache"
exclude = ["**/.temp/**", "**/.venv/**", "**/node_modules/**"]
line-length = 79
respect-gitignore = false
target-version = "py313"

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = ["D203", "D213"]
