[tool.isort]
line_length = 79
profile = "black"

[tool.black]
line-length = 79

[tool.flake8]
max-complexity = 10
max-line-length = 79

[tool.mypy]
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_unimported = true
implicit_optional = true
implicit_reexport = true
strict = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = "-s"
