[tool.poetry]
authors = ["lyouta <lyouta@spartaproject.com>"]
description = "Cleanup point cloud intuitively :D"
license = "MIT"
name = "pyspartaproj"
readme = "README.md"
version = "0.0.1"

[tool.poetry.dependencies]
paramiko = "^3.3.1"
pypiwin32 = "^223"
python = "^3.11"
python-dateutil = "^2.8.2"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
flake8-docstrings = "^1.7.0"
isort = "^5.12.0"
mypy = "^1.5.1"
pyproject-flake8 = "^6.0.0.post1"
pytest = "^7.4.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.isort]
line_length = 79
profile = "black"

[tool.black]
line-length = 79

[tool.flake8]
exclude = [".venv"]
max-complexity = 10
max-line-length = 79
