[tool.isort]
format_error = "[sparta.isort.error]:{message}"
line_length = 79
profile = "black"
quiet = true
skip = ["./poetry", "./.vscode", "./.temp", "./external", "./.git"]

[tool.black]
exclude = """(
  .poetry/ | .vscode/ | .temp/ | external/ | .git/
)"""
line-length = 79

[tool.flake8]
extend-exclude = ["./poetry", "./.vscode", "./.temp", "./external"]
ignore = [
  "PT013",
  "D401",
  "D100",
  "D101",
  "D103",
  "D105",
  "D107",
  "D102",
]
max-complexity = 10
max-doc-length = 79
max-line-length = 79

[tool.mypy]
cache_dir = "./.temp/.mypy_cache"
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_unimported = true
implicit_optional = true
implicit_reexport = true
strict = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = """
  --capture=no
  --new-first
  --ignore ./poetry
  --ignore ./external
"""
cache_dir = "./.temp/.pytest_cache"
