[tool.poetry]
authors = ["lyouta <lyouta@spartaproject.com>"]
description = "Cleanup point cloud intuitively :D"
license = "MIT"
name = "pyspartaproj"
readme = "README.md"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
flake8-bugbear = "^23.9.16"
flake8-builtins = "^2.1.0"
flake8-docstrings = "^1.7.0"
flake8-eradicate = "^1.5.0"
flake8-pytest-style = "^1.7.2"
isort = "^5.12.0"
mypy = "^1.5.1"
paramiko = "^3.3.1"
pep8-naming = "^0.13.3"
pyodide-py = "^0.24.0"
pypiwin32 = "^223"
pyproject-flake8 = "^6.1.0"
pytest = "^7.4.2"
python-dateutil = "^2.8.2"
pywin32 = "^306"
tox = "^4.11.3"
types-paramiko = "^3.3.0.0"
types-python-dateutil = "^2.8.19.14"
types-pywin32 = "^306.0.0.4"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.isort]
line_length = 79
profile = "black"

[tool.black]
line-length = 79

[tool.flake8]
max-complexity = 10
max-line-length = 79

[tool.mypy]
implicit_reexport = true
strict = true
