[project]
name = "pyspartaproj"
version = "0.0.1"
requires-python = ">=3.13.1"

[tool.uv]
dev-dependencies = [
  "mypy>=1.13.0",
  "pytest>=8.3.4",
  "ruff>=0.8.3",
  "pyspartalib",
]

[tool.uv.sources]
pyspartalib = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
cache-dir = "./.temp/.ruff_cache"
exclude = ["**/.temp/**", "**/.venv/**", "**/node_modules/**"]
line-length = 79
respect-gitignore = false
target-version = "py313"

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"

[tool.mypy]
cache_dir = "./.temp/.mypy_cache"
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_unimported = true
implicit_optional = true
implicit_reexport = true
strict = true
warn_unreachable = true

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = ["D203", "D213"]

[tool.pytest.ini_options]
addopts = """
  --quiet
  --capture=no
  --new-first
  --ignore ./docs
"""
cache_dir = "./.temp/.pytest_cache"
