[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["pyspartalib/*"]

[project]
name = "pyspartalib"
version = "0.0.11"
dependencies = [
  "chardet>=5.2.0",
  "paramiko>=3.5.0",
  "python-dateutil>=2.9.0.post0",
  "types-paramiko>=3.5.0.20240928",
  "types-python-dateutil>=2.9.0.20241206",
]
requires-python = ">=3.13.1"
authors = [{ name = "lyouta", email = "lyouta@spartaproject.com" }]
description = "Sync browser file system to local, and run Python on browser."
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["pyspartalib"]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "http://lyoutakoduka.github.io/spartaproject"
Repository = "https://github.com/lyoutakoduka/spartaproject"

[dependency-groups]
dev = ["mypy>=1.13.0", "pytest-cov>=6.0.0", "pytest>=8.3.4", "ruff>=0.8.3"]

[tool.ruff]
cache-dir = "./.temp/.ruff_cache"
exclude = [".venv", ".vscode", "docs", "tools", "pyproject.toml"]
line-length = 79
target-version = "py313"
src = ["src"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
extend-ignore = ["D203", "D213"]

[tool.mypy]
cache_dir = "./.temp/.mypy_cache"
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_unimported = true
implicit_optional = true
implicit_reexport = true
mypy_path = "src"
strict = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = """
  --quiet
  --capture=no
  --new-first
  --ignore ./docs
"""
cache_dir = "./.temp/.pytest_cache"
pythonpath = "src"
testpaths = ["tests"]
