[tool.isort]
line_length = 79
profile = "black"
quiet = true
skip = [
  "./.temp",
  "./docs",
  "./poetry",
  "./yarn",
]

[tool.black]
exclude = """(
  .temp/ |
  docs/ |
  poetry/ |
  yarn/
)"""
line-length = 79

[tool.flake8]
extend-exclude = [
  "./.temp",
  "./docs",
  "./poetry",
  "./yarn",
]
ignore = [
  "PT013",
  "D401",
]
max-complexity = 10
max-doc-length = 79
max-line-length = 79

[tool.mypy]
cache_dir = "./.temp/.mypy_cache"
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_unimported = true
implicit_optional = true
implicit_reexport = true
strict = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = """
  --quiet
  --capture=no
  --new-first
  --ignore ./docs
  --ignore ./poetry
  --ignore ./yarn
"""
cache_dir = "./.temp/.pytest_cache"
