[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["pyspartalib/*"]

[project]
name = "pyspartalib"
version = "0.0.4"
dependencies = [
]
requires-python = ">=3.10"
authors = [
    {name = "lyouta", email = "lyouta@spartaproject.com"}
]
description = "Sync browser file system to local, and run Python on browser."
readme = "README.md"
license = {file = "LICENSE"}
keywords = [
    "pyspartalib"
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.10"
]

[project.urls]
Homepage = "http://lyoutakoduka.github.io/spartaproject"
Repository = "https://github.com/lyoutakoduka/spartaproject"

[tool.isort]
line_length = 79
profile = "black"
quiet = true
skip = [
  "./.temp",
  "./docs",
  "./poetry"
]

[tool.black]
exclude = """(
  .temp/ |
  docs/ |
  poetry/
)"""
line-length = 79

[tool.flake8]
extend-exclude = [
  "./.temp",
  "./docs",
  "./poetry"
]
ignore = [
  "PT013",
  "D401",
]
max-complexity = 10
max-doc-length = 79
max-line-length = 79

[tool.mypy]
cache_dir = "./.temp/.mypy_cache"
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_unimported = true
implicit_optional = true
implicit_reexport = true
strict = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = """
  --quiet
  --capture=no
  --new-first
  --ignore ./docs
  --ignore ./poetry
"""
cache_dir = "./.temp/.pytest_cache"
pythonpath = "src"
testpaths = ["tests"]
