[tool.isort]
line_length = 79
profile = "black"

[tool.black]
line-length = 79

[tool.flake8]
extend-exclude = ["./temporary", "./poetry"]
ignore = [
  "PT013",
  "D401",
  "D100",
  "D101",
  "D103",
  "D105",
  "D107",
  "D102",
  "A001",
  "A002",
]
max-complexity = 10
max-doc-length = 79
max-line-length = 79

[tool.mypy]
cache_dir = "./temporary/.mypy_cache"
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_unimported = true
implicit_optional = true
implicit_reexport = true
strict = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = "--capture=no --exitfirst --new-first --quiet"
cache_dir = "./temporary/.pytest_cache"
testpaths = ["test"]
