[chrome]

chrome.development = """
& 'C:/***/chrome.exe' --disable-web-security --user-data-dir
"""

wget = """
sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
"""

apt.fix = """
sudo apt --fix-broken install
"""

dpkg.install = """
sudo dpkg --install google-chrome-stable_current_amd64.deb
"""
