[linux.make]

apt.install.gcc = """
sudo apt install gcc
"""

apt.install.make = """
sudo apt install make
"""

configure = """
./configure
"""

make = """
make
"""

make.install = """
sudo make install
"""
