[linux.other]

mount.types = """
sudo mount --types drvfs g: /mnt/g
"""

chmod.access = """
chmod 755 tools/tool.sh
"""

history = """
history
"""

touch = """
touch index.html
"""

rsync = """
sudo rsync --verbose --archive --progress --stats /***/*.html /var/www/html
"""
