[wsl.other]

wsl.update = """
wsl --update
"""

wsl.list = """
wsl --list
"""

wsl.install = """
wsl --install Ubuntu
"""

wsl.terminate = """
wsl --terminate Ubuntu
"""

wsl.unregister = """
wsl --unregister Ubuntu
"""

wsl.distribution = """
wsl --distribution Ubuntu_22_04 --user root
"""

wsl.default = """
wsl --set-default Ubuntu_22_04
"""
