services:
  dev:
    volumes:
      - ..:/workspace:delegated
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: 24.04
    env_file:
      - devcontainer.env
