[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src/*"]

[project]
name = "pyspartalib"
version = "0.0.13"
dependencies = [
  "chardet>=5.2.0",
  "paramiko>=3.5.0",
  "pytest>=8.3.4",
  "python-dateutil>=2.9.0.post0",
  "types-paramiko>=3.5.0.20240928",
  "types-python-dateutil>=2.9.0.20241206",
]
requires-python = ">=3.13.1"
authors = [{ name = "lyouta", email = "lyouta@spartaproject.com" }]
description = "Sync browser file system to local, and run Python on browser."
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["pyspartalib"]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "http://lyoutakoduka.github.io/spartaproject"
Repository = "https://github.com/lyoutakoduka/spartaproject"
